# Generated by Django 5.2.14 on 2026-05-14 00:20

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='diagnostic_photos')),
                ('description', models.TextField()),
                ('llm_provider', models.CharField(choices=[('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('glm', 'GLM')], default='groq', max_length=20)),
                ('llm_response', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(blank=True, choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('urgente', 'Urgente')], max_length=20)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='processando', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-created_at'],
            },
        ),
    ]
