# Generated by Django 5.2.14 on 2026-05-14 00:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('workshop_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('km_at_service', models.PositiveIntegerField(blank=True, null=True)),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='receipts/')),
            ],
            options={
                'verbose_name': 'Registro de Manutenção',
                'verbose_name_plural': 'Registros de Manutenção',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('oleo', 'Troca de Óleo'), ('pneu', 'Pneus'), ('revisao', 'Revisão Geral'), ('freio', 'Freios'), ('correia', 'Correia Dentada'), ('ipva', 'IPVA'), ('seguro', 'Seguro'), ('licenciamento', 'Licenciamento'), ('outro', 'Outro')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_km', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lembrete de Manutenção',
                'verbose_name_plural': 'Lembretes de Manutenção',
                'ordering': ['due_date', 'due_km'],
            },
        ),
    ]
