# Generated by Django 5.2.14 on 2026-05-14 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='maintenancereminder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='maintenance.maintenancereminder'),
        ),
    ]
